typedef enum Token {
  TOKEN_HTML_TAG,
  TOKEN_HEAD_TAG,
  TOKEN_BODY_TAG,
  TOKEN_TITLE_TAG,
  TOKEN_META_TAG,
  TOKEN_DIV_TAG,
  TOKEN_H1_TAG,
  TOKEN_P_TAG,
  TOKEN_A_TAG,
  TOKEN_BRACKET_OPEN,
  TOKEN_BRACKET_CLOSE,
  TOKEN_BRACE_OPEN,
  TOKEN_BRACE_CLOSE,
  TOKEN_PARENTHESIS_OPEN,
  TOKEN_PARENTHESIS_CLOSE,
  TOKEN_UNRECOGNIZED
} Token;

enum Token token_identify(const char *str);
